# DATA SCIENCE WITH PYTHON 

PYTHON LIBRARIES

In [1]:
print("hello world")

hello world


In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
import time
import sys

In [6]:
b=range(1000)
print(sys.getsizeof(5)* len(b))

28000


In [7]:
 size = 1000

In [9]:
L1 = range(size)
L2 = range(size)
A1 = np.arange(size)
A2 = np.arange(size)

In [11]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
a.ndim

2

In [14]:
a.itemsize

8

In [15]:
a.shape

(3, 2)

In [16]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])